openapi: 3.0.2
info:
  title: mock-api
  version: 1
  description: Mock API definitions.
servers:
  -
    url: '/'
paths:
  /users:
    get:
      responses:
        '200':
          description: OK
  /test:
    get:
      responses:
        '200':
          description: OK
  /test2:
    get:
      responses:
        '200':
          description: OK
  /test-post:
    post:
      responses:
        "200":
          description: OK
  /test-put:
    put:
      responses:
        "200":
          description: OK
  /test-delete:
    delete:
      responses:
        "200":
          description: OK
          